/*
 * File: app/view/MyNavigationView.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ThatConference.view.MyNavigationView', {
    extend: 'Ext.navigation.View',

    config: {
        items: [
            {
                xtype: 'list',
                itemId: 'AttendeeList',
                itemTpl: [
                    '<div>{name}</div>'
                ],
                store: 'Attendees',
                title: 'ThatConference 2012'
            }
        ],
        listeners: [
            {
                fn: 'onAttendeeListItemTap',
                event: 'itemtap',
                delegate: '#AttendeeList'
            }
        ]
    },

    onAttendeeListItemTap: function(dataview, index, target, record, e, options) {
        console.log(record.get('name'));
    }

});